POST {{host}}/telegraph/{{botToken}}/webhook
Accept: application/json
Content-Type: application/json

{
    "update_id": 605131020,
    "message": {
        "message_id": 194,
        "from": {
            "id": 62626897,
            "is_bot": false,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "language_code": "ru"
        },
        "chat": {
            "id": 62626897,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "type": "private"
        },
        "date": 1668722514,
        "animation": {
            "file_name": "seal-waiting.mp4",
            "mime_type": "video/mp4",
            "duration": 8,
            "width": 148,
            "height": 148,
            "thumb": {
                "file_id": "AAMCBAADGQEAA8Jjdq9SPkpdjuAHsQFvQD12LrncGwACLgMAAuQUBFMdKDRcsstZHQEAB20AAysE",
                "file_unique_id": "AQADLgMAAuQUBFNy",
                "file_size": 4067,
                "width": 148,
                "height": 148
            },
            "file_id": "CgACAgQAAxkBAAPCY3avUj5KXY7gB7EBb0A9di653BsAAi4DAALkFARTHSg0XLLLWR0rBA",
            "file_unique_id": "AgADLgMAAuQUBFM",
            "file_size": 28035
        },
        "document": {
            "file_name": "seal-waiting.mp4",
            "mime_type": "video/mp4",
            "thumb": {
                "file_id": "AAMCBAADGQEAA8Jjdq9SPkpdjuAHsQFvQD12LrncGwACLgMAAuQUBFMdKDRcsstZHQEAB20AAysE",
                "file_unique_id": "AQADLgMAAuQUBFNy",
                "file_size": 4067,
                "width": 148,
                "height": 148
            },
            "file_id": "CgACAgQAAxkBAAPCY3avUj5KXY7gB7EBb0A9di653BsAAi4DAALkFARTHSg0XLLLWR0rBA",
            "file_unique_id": "AgADLgMAAuQUBFM",
            "file_size": 28035
        }
    }
}
