POST {{host}}/telegraph/{{botToken}}/webhook
Accept: application/json
Content-Type: application/json

{
    "update_id": 605131024,
    "message": {
        "message_id": 199,
        "from": {
            "id": 62626897,
            "is_bot": false,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "language_code": "ru"
        },
        "chat": {
            "id": 62626897,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "type": "private"
        },
        "date": 1668722779,
        "document": {
            "file_name": "qwerty.log",
            "mime_type": "text/x-log",
            "file_id": "BQACAgIAAxkBAAPHY3awWzuK77yJghmbpZs1iTLaZCoAAtIeAAI3BLlLvZzJEbbFRr8rBA",
            "file_unique_id": "AgAD0h4AAjcEuUs",
            "file_size": 6
        },
        "caption": "This is a description of the document message 💪"
    }
}
