POST {{host}}/telegraph/{{botToken}}/webhook
Accept: application/json
Content-Type: application/json

{
    "update_id": 605131031,
    "message": {
        "message_id": 206,
        "from": {
            "id": 62626897,
            "is_bot": false,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "language_code": "ru"
        },
        "chat": {
            "id": 62626897,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "type": "private"
        },
        "date": 1668723152,
        "sticker": {
            "width": 512,
            "height": 512,
            "emoji": "🔥",
            "set_name": "cat_Teftel_animated",
            "is_animated": true,
            "is_video": false,
            "type": "regular",
            "thumb": {
                "file_id": "AAMCAgADGQEAA85jdrHQgBMfWmUC-iEpdpSejXO9OQACwgQAAiBtOwABiVOqr39ABMABAAdtAAMrBA",
                "file_unique_id": "AQADwgQAAiBtOwABcg",
                "file_size": 5116,
                "width": 128,
                "height": 128
            },
            "file_id": "CAACAgIAAxkBAAPOY3ax0IATH1plAvohKXaUno1zvTkAAsIEAAIgbTsAAYlTqq9_QATAKwQ",
            "file_unique_id": "AgADwgQAAiBtOwAB",
            "file_size": 2813
        }
    }
}
