POST {{host}}/telegraph/{{botToken}}/webhook
Accept: application/json
Content-Type: application/json

{
    "update_id": 605131033,
    "message": {
        "message_id": 208,
        "from": {
            "id": 62626897,
            "is_bot": false,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "language_code": "ru"
        },
        "chat": {
            "id": 62626897,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "type": "private"
        },
        "date": 1668723246,
        "text": "текстовое сообщение с эмодзи и кодом 😊",
        "entities": [
            {
                "offset": 31,
                "length": 5,
                "type": "code"
            }
        ]
    }
}
