POST {{host}}/telegraph/{{botToken}}/webhook
Accept: application/json
Content-Type: application/json

{
    "update_id": 605131035,
    "message": {
        "message_id": 210,
        "from": {
            "id": 62626897,
            "is_bot": false,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "language_code": "ru"
        },
        "chat": {
            "id": 62626897,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "type": "private"
        },
        "date": 1668723377,
        "video_note": {
            "duration": 3,
            "length": 384,
            "thumb": {
                "file_id": "AAMCAgADGQEAA9JjdrKxbygvjgABYLsy-9wRNImzoOwAAtYeAAI3BLlL6I4f1JRtGIIBAAdtAAMrBA",
                "file_unique_id": "AQAD1h4AAjcEuUty",
                "file_size": 6772,
                "width": 320,
                "height": 320
            },
            "file_id": "DQACAgIAAxkBAAPSY3aysW8oL44AAWC7MvvcETSJs6DsAALWHgACNwS5S-iOH9SUbRiCKwQ",
            "file_unique_id": "AgAD1h4AAjcEuUs",
            "file_size": 87019
        }
    }
}
