POST {{host}}/telegraph/{{botToken}}/webhook
Accept: application/json
Content-Type: application/json

{
    "update_id": 605131023,
    "message": {
        "message_id": 198,
        "from": {
            "id": 62626897,
            "is_bot": false,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "language_code": "ru"
        },
        "chat": {
            "id": 62626897,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "type": "private"
        },
        "date": 1668722711,
        "contact": {
            "phone_number": "+74957830979",
            "first_name": "Converse",
            "vcard": "BEGIN:VCARD VERSION:3.0 FN:Converse TEL;TYPE=CELL:+74957830979 END:VCARD"
        }
    }
}
