POST {{host}}/telegraph/{{botToken}}/webhook
Accept: application/json
Content-Type: application/json

{
    "update_id": 605131038,
    "message": {
        "message_id": 213,
        "from": {
            "id": 62626897,
            "is_bot": false,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "language_code": "ru"
        },
        "chat": {
            "id": 62626897,
            "first_name": "Andrey",
            "last_name": "Helldar",
            "username": "Helldar",
            "type": "private"
        },
        "date": 1668723585,
        "video": {
            "duration": 4,
            "width": 720,
            "height": 1280,
            "mime_type": "video/mp4",
            "thumb": {
                "file_id": "AAMCAgADGQEAA9VjdrOBO9tKDCzJcFiz7w8NWuoh_gAC1R4AAjcEuUvSEgdXE9aPmAEAB20AAysE",
                "file_unique_id": "AQAD1R4AAjcEuUty",
                "file_size": 12322,
                "width": 180,
                "height": 320
            },
            "file_id": "BAACAgIAAxkBAAPVY3azgTvbSgwsyXBYs-8PDVrqIf4AAtUeAAI3BLlL0hIHVxPWj5grBA",
            "file_unique_id": "AgAD1R4AAjcEuUs",
            "file_size": 1500799
        },
        "caption": "qwerty"
    }
}
